version: '2.1'

services:

  customer-service:
    build: ./index
    restart: always
    ports:
      - "1002:1002"
    networks:
      - overlay

  book-service:
    build: ./login
    restart: always
    ports:
      - "1003:1003"
    networks:
      - overlay

  lend-service:
    build: ./Menu
    restart: always
    ports:
      - "1004:1004"
    networks:
      - overlay

  api:
    build: ./Promocion
    restart: always
    ports:
      - "1005:1005"
    networks: 
      - overlay

networks:
  overlay:
    